const FRENCH_DATA = {
  language: 'French',
  langCode: 'fr-FR',
  flag: '🇫🇷',
  color: '#002395',
  accent: '#ED2939',

  words: [
    // GREETINGS
    { id: 1, category: 'Greetings', foreign: 'Bonjour', english: 'Hello / Good morning', pronunciation: 'bohn-ZHOOR' },
    { id: 2, category: 'Greetings', foreign: 'Bonsoir', english: 'Good evening', pronunciation: 'bohn-SWAHR' },
    { id: 3, category: 'Greetings', foreign: 'Bonne nuit', english: 'Good night', pronunciation: 'bohn NWEE' },
    { id: 4, category: 'Greetings', foreign: 'Salut', english: 'Hi (informal)', pronunciation: 'sah-LUE' },
    { id: 5, category: 'Greetings', foreign: 'Au revoir', english: 'Goodbye', pronunciation: 'oh ruh-VWAHR' },
    { id: 6, category: 'Greetings', foreign: 'Merci', english: 'Thank you', pronunciation: 'mehr-SEE' },
    { id: 7, category: 'Greetings', foreign: "S'il vous plaît", english: 'Please (formal)', pronunciation: 'seel voo PLEH' },
    { id: 8, category: 'Greetings', foreign: 'De rien', english: "You're welcome", pronunciation: 'duh ree-AN' },
    { id: 9, category: 'Greetings', foreign: 'Oui', english: 'Yes', pronunciation: 'WEE' },
    { id: 10, category: 'Greetings', foreign: 'Non', english: 'No', pronunciation: 'NOH' },

    // ESSENTIALS
    { id: 11, category: 'Essentials', foreign: 'Excusez-moi', english: 'Excuse me', pronunciation: 'ex-kew-ZAY mwah' },
    { id: 12, category: 'Essentials', foreign: 'Pardon', english: 'Sorry / Pardon', pronunciation: 'par-DOH' },
    { id: 13, category: 'Essentials', foreign: 'Je', english: 'I', pronunciation: 'zhuh' },
    { id: 14, category: 'Essentials', foreign: 'Vous', english: 'You (formal)', pronunciation: 'VOO' },
    { id: 15, category: 'Essentials', foreign: 'Tu', english: 'You (informal)', pronunciation: 'tew' },
    { id: 16, category: 'Essentials', foreign: 'Nous', english: 'We', pronunciation: 'NOO' },
    { id: 17, category: 'Essentials', foreign: 'Ici', english: 'Here', pronunciation: 'ee-SEE' },
    { id: 18, category: 'Essentials', foreign: 'Là', english: 'There', pronunciation: 'LAH' },
    { id: 19, category: 'Essentials', foreign: 'Où', english: 'Where', pronunciation: 'OO' },
    { id: 20, category: 'Essentials', foreign: 'Quoi', english: 'What', pronunciation: 'KWAH' },

    // NUMBERS
    { id: 21, category: 'Numbers', foreign: 'Un', english: 'One', pronunciation: 'UH' },
    { id: 22, category: 'Numbers', foreign: 'Deux', english: 'Two', pronunciation: 'DUH' },
    { id: 23, category: 'Numbers', foreign: 'Trois', english: 'Three', pronunciation: 'TWAH' },
    { id: 24, category: 'Numbers', foreign: 'Quatre', english: 'Four', pronunciation: 'KAT-ruh' },
    { id: 25, category: 'Numbers', foreign: 'Cinq', english: 'Five', pronunciation: 'SANK' },
    { id: 26, category: 'Numbers', foreign: 'Six', english: 'Six', pronunciation: 'SEES' },
    { id: 27, category: 'Numbers', foreign: 'Sept', english: 'Seven', pronunciation: 'SET' },
    { id: 28, category: 'Numbers', foreign: 'Huit', english: 'Eight', pronunciation: 'WEET' },
    { id: 29, category: 'Numbers', foreign: 'Neuf', english: 'Nine', pronunciation: 'NUF' },
    { id: 30, category: 'Numbers', foreign: 'Dix', english: 'Ten', pronunciation: 'DEES' },

    // FOOD & DRINK
    { id: 31, category: 'Food & Drink', foreign: 'Pain', english: 'Bread', pronunciation: 'PAN' },
    { id: 32, category: 'Food & Drink', foreign: 'Eau', english: 'Water', pronunciation: 'OH' },
    { id: 33, category: 'Food & Drink', foreign: 'Vin', english: 'Wine', pronunciation: 'VAN' },
    { id: 34, category: 'Food & Drink', foreign: 'Café', english: 'Coffee', pronunciation: 'ka-FAY' },
    { id: 35, category: 'Food & Drink', foreign: 'Fromage', english: 'Cheese', pronunciation: 'froh-MAZH' },
    { id: 36, category: 'Food & Drink', foreign: 'Poulet', english: 'Chicken', pronunciation: 'poo-LAY' },
    { id: 37, category: 'Food & Drink', foreign: 'Poisson', english: 'Fish', pronunciation: 'pwah-SON' },
    { id: 38, category: 'Food & Drink', foreign: 'Bière', english: 'Beer', pronunciation: 'bee-AIR' },
    { id: 39, category: 'Food & Drink', foreign: 'Thé', english: 'Tea', pronunciation: 'TAY' },
    { id: 40, category: 'Food & Drink', foreign: 'Dessert', english: 'Dessert', pronunciation: 'deh-ZAIR' },

    // TRANSPORT
    { id: 41, category: 'Transport', foreign: 'Taxi', english: 'Taxi', pronunciation: 'tak-SEE' },
    { id: 42, category: 'Transport', foreign: 'Bus', english: 'Bus', pronunciation: 'BOOS' },
    { id: 43, category: 'Transport', foreign: 'Train', english: 'Train', pronunciation: 'TRAN' },
    { id: 44, category: 'Transport', foreign: 'Métro', english: 'Subway', pronunciation: 'may-TROH' },
    { id: 45, category: 'Transport', foreign: 'Gare', english: 'Train station', pronunciation: 'GAR' },
    { id: 46, category: 'Transport', foreign: 'Aéroport', english: 'Airport', pronunciation: 'ah-ay-roh-POR' },
    { id: 47, category: 'Transport', foreign: 'Hôtel', english: 'Hotel', pronunciation: 'oh-TEL' },
    { id: 48, category: 'Transport', foreign: 'Rue', english: 'Street', pronunciation: 'ROO' },
    { id: 49, category: 'Transport', foreign: 'Gauche', english: 'Left', pronunciation: 'GOHSH' },
    { id: 50, category: 'Transport', foreign: 'Droite', english: 'Right', pronunciation: 'DRWAHT' },

    // TIME
    { id: 51, category: 'Time', foreign: "Aujourd'hui", english: 'Today', pronunciation: 'oh-zhoor-DWEE' },
    { id: 52, category: 'Time', foreign: 'Demain', english: 'Tomorrow', pronunciation: 'duh-MAN' },
    { id: 53, category: 'Time', foreign: 'Hier', english: 'Yesterday', pronunciation: 'ee-AIR' },
    { id: 54, category: 'Time', foreign: 'Matin', english: 'Morning', pronunciation: 'ma-TAN' },
    { id: 55, category: 'Time', foreign: 'Soir', english: 'Evening', pronunciation: 'SWAHR' },
    { id: 56, category: 'Time', foreign: 'Heure', english: 'Hour / Time', pronunciation: 'URR' },
    { id: 57, category: 'Time', foreign: 'Maintenant', english: 'Now', pronunciation: 'man-tuh-NON' },
    { id: 58, category: 'Time', foreign: 'Bientôt', english: 'Soon', pronunciation: 'bee-an-TOH' },
    { id: 59, category: 'Time', foreign: 'Lundi', english: 'Monday', pronunciation: 'lun-DEE' },
    { id: 60, category: 'Time', foreign: 'Semaine', english: 'Week', pronunciation: 'suh-MEN' },

    // ADJECTIVES
    { id: 61, category: 'Adjectives', foreign: 'Bon', english: 'Good', pronunciation: 'BOH' },
    { id: 62, category: 'Adjectives', foreign: 'Grand', english: 'Big / Tall', pronunciation: 'GRON' },
    { id: 63, category: 'Adjectives', foreign: 'Petit', english: 'Small', pronunciation: 'puh-TEE' },
    { id: 64, category: 'Adjectives', foreign: 'Beau', english: 'Beautiful', pronunciation: 'BOH' },
    { id: 65, category: 'Adjectives', foreign: 'Cher', english: 'Expensive', pronunciation: 'SHAIR' },
    { id: 66, category: 'Adjectives', foreign: 'Libre', english: 'Free / Available', pronunciation: 'LEE-bruh' },
    { id: 67, category: 'Adjectives', foreign: 'Ouvert', english: 'Open', pronunciation: 'oo-VAIR' },
    { id: 68, category: 'Adjectives', foreign: 'Fermé', english: 'Closed', pronunciation: 'fair-MAY' },
    { id: 69, category: 'Adjectives', foreign: 'Chaud', english: 'Hot', pronunciation: 'SHOH' },
    { id: 70, category: 'Adjectives', foreign: 'Froid', english: 'Cold', pronunciation: 'FWAH' },

    // VERBS
    { id: 71, category: 'Verbs', foreign: 'Avoir', english: 'To have', pronunciation: 'ah-VWAHR' },
    { id: 72, category: 'Verbs', foreign: 'Être', english: 'To be', pronunciation: 'EH-truh' },
    { id: 73, category: 'Verbs', foreign: 'Aller', english: 'To go', pronunciation: 'ah-LAY' },
    { id: 74, category: 'Verbs', foreign: 'Vouloir', english: 'To want', pronunciation: 'voo-LWAHR' },
    { id: 75, category: 'Verbs', foreign: 'Pouvoir', english: 'To be able to', pronunciation: 'poo-VWAHR' },
    { id: 76, category: 'Verbs', foreign: 'Savoir', english: 'To know', pronunciation: 'sah-VWAHR' },
    { id: 77, category: 'Verbs', foreign: 'Faire', english: 'To do / make', pronunciation: 'FAIR' },
    { id: 78, category: 'Verbs', foreign: 'Venir', english: 'To come', pronunciation: 'vuh-NEER' },
    { id: 79, category: 'Verbs', foreign: 'Parler', english: 'To speak', pronunciation: 'par-LAY' },
    { id: 80, category: 'Verbs', foreign: 'Comprendre', english: 'To understand', pronunciation: 'kom-PRON-druh' },

    // SHOPPING
    { id: 81, category: 'Shopping', foreign: 'Combien', english: 'How much', pronunciation: 'kom-bee-AN' },
    { id: 82, category: 'Shopping', foreign: 'Prix', english: 'Price', pronunciation: 'PREE' },
    { id: 83, category: 'Shopping', foreign: 'Magasin', english: 'Store', pronunciation: 'ma-ga-ZAN' },
    { id: 84, category: 'Shopping', foreign: 'Marché', english: 'Market', pronunciation: 'mar-SHAY' },
    { id: 85, category: 'Shopping', foreign: 'Acheter', english: 'To buy', pronunciation: 'ash-TAY' },
    { id: 86, category: 'Shopping', foreign: 'Argent', english: 'Money', pronunciation: 'ar-ZHON' },
    { id: 87, category: 'Shopping', foreign: 'Carte', english: 'Card', pronunciation: 'KART' },
    { id: 88, category: 'Shopping', foreign: 'Reçu', english: 'Receipt', pronunciation: 'ruh-SEW' },
    { id: 89, category: 'Shopping', foreign: 'Taille', english: 'Size', pronunciation: 'TIE' },
    { id: 90, category: 'Shopping', foreign: 'Réduction', english: 'Discount', pronunciation: 'ray-dook-see-ON' },

    // EMERGENCY
    { id: 91, category: 'Emergency', foreign: 'Aide', english: 'Help', pronunciation: 'AID' },
    { id: 92, category: 'Emergency', foreign: 'Médecin', english: 'Doctor', pronunciation: 'may-duh-SAN' },
    { id: 93, category: 'Emergency', foreign: 'Hôpital', english: 'Hospital', pronunciation: 'oh-pee-TAL' },
    { id: 94, category: 'Emergency', foreign: 'Police', english: 'Police', pronunciation: 'po-LEES' },
    { id: 95, category: 'Emergency', foreign: 'Urgence', english: 'Emergency', pronunciation: 'ur-ZHONS' },
    { id: 96, category: 'Emergency', foreign: 'Perdu', english: 'Lost', pronunciation: 'pair-DEW' },
    { id: 97, category: 'Emergency', foreign: 'Malade', english: 'Sick', pronunciation: 'ma-LAD' },
    { id: 98, category: 'Emergency', foreign: 'Douleur', english: 'Pain', pronunciation: 'doo-LUR' },
    { id: 99, category: 'Emergency', foreign: 'Toilettes', english: 'Restroom', pronunciation: 'twah-LET' },
    { id: 100, category: 'Emergency', foreign: 'Ambassade', english: 'Embassy', pronunciation: 'am-ba-SAD' },
  ],

  phrases: [
    // GREETINGS & INTRODUCTIONS
    { id: 1, category: 'Greetings & Introductions', foreign: 'Bonjour, comment allez-vous?', english: 'Hello, how are you? (formal)', pronunciation: 'bohn-ZHOOR, ko-MON ta-LAY voo' },
    { id: 2, category: 'Greetings & Introductions', foreign: 'Salut, ça va?', english: "Hi, how's it going? (informal)", pronunciation: 'sa-LEW, sa VA' },
    { id: 3, category: 'Greetings & Introductions', foreign: 'Ça va bien, merci.', english: "I'm doing well, thank you.", pronunciation: 'sa va bee-AN, mehr-SEE' },
    { id: 4, category: 'Greetings & Introductions', foreign: 'Et vous?', english: 'And you? (formal)', pronunciation: 'ay VOO' },
    { id: 5, category: 'Greetings & Introductions', foreign: 'Je m\'appelle Diego.', english: 'My name is Diego.', pronunciation: 'zhuh ma-PEL Diego' },
    { id: 6, category: 'Greetings & Introductions', foreign: 'Enchanté(e).', english: 'Nice to meet you.', pronunciation: 'on-shon-TAY' },
    { id: 7, category: 'Greetings & Introductions', foreign: 'Comment vous appelez-vous?', english: 'What is your name? (formal)', pronunciation: 'ko-MON voo za-play VOO' },
    { id: 8, category: 'Greetings & Introductions', foreign: 'Ravi de vous rencontrer.', english: 'Pleased to meet you.', pronunciation: 'ra-VEE duh voo ron-kon-TRAY' },
    { id: 9, category: 'Greetings & Introductions', foreign: 'Bonne journée!', english: 'Have a good day!', pronunciation: 'bohn zhoor-NAY' },
    { id: 10, category: 'Greetings & Introductions', foreign: 'À bientôt!', english: 'See you soon!', pronunciation: 'ah bee-an-TOH' },
    { id: 11, category: 'Greetings & Introductions', foreign: 'À demain!', english: 'See you tomorrow!', pronunciation: 'ah duh-MAN' },
    { id: 12, category: 'Greetings & Introductions', foreign: 'Bonne soirée!', english: 'Have a good evening!', pronunciation: 'bohn swah-RAY' },

    // ABOUT YOURSELF
    { id: 13, category: 'About Yourself', foreign: 'Je suis américain(e).', english: 'I am American.', pronunciation: 'zhuh swee za-may-ree-KAN' },
    { id: 14, category: 'About Yourself', foreign: 'Je viens des États-Unis.', english: 'I come from the United States.', pronunciation: 'zhuh vee-AN day zay-ta-zoo-NEE' },
    { id: 15, category: 'About Yourself', foreign: "J'apprends le français.", english: 'I am learning French.', pronunciation: 'zha-PRON luh fron-SAY' },
    { id: 16, category: 'About Yourself', foreign: 'Mon français n\'est pas très bon.', english: 'My French is not very good.', pronunciation: 'mon fron-SAY nay pa tray BON' },
    { id: 17, category: 'About Yourself', foreign: 'Je parle un peu français.', english: 'I speak a little French.', pronunciation: 'zhuh PARL un puh fron-SAY' },
    { id: 18, category: 'About Yourself', foreign: 'Mon espagnol et mon anglais sont meilleurs.', english: 'My Spanish and English are better.', pronunciation: 'mon es-pa-NYOL ay mon on-GLAY son may-YUR' },
    { id: 19, category: 'About Yourself', foreign: 'Pouvez-vous parler plus lentement?', english: 'Can you speak more slowly?', pronunciation: 'poo-VAY voo par-LAY plew lon-tuh-MON' },
    { id: 20, category: 'About Yourself', foreign: 'Je ne comprends pas.', english: "I don't understand.", pronunciation: 'zhuh nuh kom-PRON pa' },
    { id: 21, category: 'About Yourself', foreign: 'Pouvez-vous répéter?', english: 'Can you repeat that?', pronunciation: 'poo-VAY voo ray-pay-TAY' },
    { id: 22, category: 'About Yourself', foreign: 'Parlez-vous anglais?', english: 'Do you speak English?', pronunciation: 'par-LAY voo on-GLAY' },

    // CONVERSATION STARTERS
    { id: 23, category: 'Conversation Starters', foreign: 'D\'où venez-vous?', english: 'Where are you from?', pronunciation: 'DOO vuh-NAY voo' },
    { id: 24, category: 'Conversation Starters', foreign: 'Quel est votre métier?', english: 'What do you do for work?', pronunciation: 'kel ay VOT-ruh may-tee-AY' },
    { id: 25, category: 'Conversation Starters', foreign: 'C\'est votre première fois en France?', english: 'Is this your first time in France?', pronunciation: 'say VOT-ruh pruh-MYER fwah on FRONS' },
    { id: 26, category: 'Conversation Starters', foreign: 'Vous aimez la France?', english: 'Do you like France?', pronunciation: 'voo zay-MAY la FRONS' },
    { id: 27, category: 'Conversation Starters', foreign: 'Qu\'est-ce que vous recommandez?', english: 'What do you recommend?', pronunciation: 'kes kuh voo ruh-ko-man-DAY' },
    { id: 28, category: 'Conversation Starters', foreign: 'C\'est magnifique ici.', english: "It's beautiful here.", pronunciation: 'say mahn-yee-FEEK ee-SEE' },
    { id: 29, category: 'Conversation Starters', foreign: "J'adore Paris.", english: 'I love Paris.', pronunciation: 'zha-DOR pa-REE' },
    { id: 30, category: 'Conversation Starters', foreign: 'La cuisine française est délicieuse.', english: 'French cuisine is delicious.', pronunciation: 'la kwee-ZEEN fron-SEZ ay day-lee-see-UHZ' },
    { id: 31, category: 'Conversation Starters', foreign: 'Quel temps fait-il?', english: "What's the weather like?", pronunciation: 'kel tOM fay TEEL' },
    { id: 32, category: 'Conversation Starters', foreign: 'Vous avez des enfants?', english: 'Do you have children?', pronunciation: 'voo za-VAY day zon-FON' },

    // FOOD & ORDERING
    { id: 33, category: 'Food & Ordering', foreign: 'Une table pour deux, s\'il vous plaît.', english: 'A table for two, please.', pronunciation: 'ewn TA-bluh poor DUH, seel voo PLEH' },
    { id: 34, category: 'Food & Ordering', foreign: 'La carte, s\'il vous plaît.', english: 'The menu, please.', pronunciation: 'la KART, seel voo PLEH' },
    { id: 35, category: 'Food & Ordering', foreign: 'Je voudrais commander.', english: 'I would like to order.', pronunciation: 'zhuh voo-DRAY ko-mon-DAY' },
    { id: 36, category: 'Food & Ordering', foreign: 'Je prends le plat du jour.', english: "I'll have the daily special.", pronunciation: 'zhuh PRON luh pla dew ZHOOR' },
    { id: 37, category: 'Food & Ordering', foreign: 'C\'est quoi la spécialité?', english: "What's the specialty?", pronunciation: 'say KWAH la spay-see-a-lee-TAY' },
    { id: 38, category: 'Food & Ordering', foreign: "L'addition, s'il vous plaît.", english: 'The bill, please.', pronunciation: 'la-dee-see-ON, seel voo PLEH' },
    { id: 39, category: 'Food & Ordering', foreign: "C'est délicieux!", english: "It's delicious!", pronunciation: 'say day-lee-see-UH' },
    { id: 40, category: 'Food & Ordering', foreign: 'Je suis allergique à...', english: 'I am allergic to...', pronunciation: 'zhuh swee za-lair-ZHEEK ah' },
    { id: 41, category: 'Food & Ordering', foreign: 'Un verre de vin rouge, s\'il vous plaît.', english: 'A glass of red wine, please.', pronunciation: 'un VAIR duh van ROOZH, seel voo PLEH' },
    { id: 42, category: 'Food & Ordering', foreign: "De l'eau, s'il vous plaît.", english: 'Some water, please.', pronunciation: 'duh LOH, seel voo PLEH' },
    { id: 43, category: 'Food & Ordering', foreign: 'Est-ce que le service est inclus?', english: 'Is the service charge included?', pronunciation: 'es kuh luh sair-VEES ay tan-KLEW' },
    { id: 44, category: 'Food & Ordering', foreign: 'Je ne mange pas de viande.', english: "I don't eat meat.", pronunciation: 'zhuh nuh MONZH pa duh vee-OND' },

    // DIRECTIONS & TRANSPORT
    { id: 45, category: 'Directions & Transport', foreign: 'Où est la gare?', english: 'Where is the train station?', pronunciation: 'oo ay la GAR' },
    { id: 46, category: 'Directions & Transport', foreign: 'Comment aller à...?', english: 'How do I get to...?', pronunciation: 'ko-MON ta-LAY ah' },
    { id: 47, category: 'Directions & Transport', foreign: 'À gauche / À droite.', english: 'To the left / To the right.', pronunciation: 'ah GOHSH / ah DRWAHT' },
    { id: 48, category: 'Directions & Transport', foreign: 'Tout droit.', english: 'Straight ahead.', pronunciation: 'too DRWAH' },
    { id: 49, category: 'Directions & Transport', foreign: 'C\'est loin?', english: 'Is it far?', pronunciation: 'say LWAN' },
    { id: 50, category: 'Directions & Transport', foreign: 'Appelez-moi un taxi, s\'il vous plaît.', english: 'Please call me a taxi.', pronunciation: 'ap-LAY mwah un tak-SEE, seel voo PLEH' },
    { id: 51, category: 'Directions & Transport', foreign: 'À l\'aéroport, s\'il vous plaît.', english: 'To the airport, please.', pronunciation: 'ah la-ay-roh-POR, seel voo PLEH' },
    { id: 52, category: 'Directions & Transport', foreign: 'Un billet pour..., s\'il vous plaît.', english: 'A ticket to..., please.', pronunciation: 'un bee-YAY poor, seel voo PLEH' },
    { id: 53, category: 'Directions & Transport', foreign: 'À quelle heure part le train?', english: 'What time does the train leave?', pronunciation: 'ah kel UR par luh TRAN' },
    { id: 54, category: 'Directions & Transport', foreign: 'Je suis perdu(e).', english: 'I am lost.', pronunciation: 'zhuh swee pair-DEW' },

    // SHOPPING
    { id: 55, category: 'Shopping', foreign: 'Combien ça coûte?', english: 'How much does it cost?', pronunciation: 'kom-bee-AN sa KOOT' },
    { id: 56, category: 'Shopping', foreign: 'C\'est trop cher.', english: "It's too expensive.", pronunciation: 'say troh SHAIR' },
    { id: 57, category: 'Shopping', foreign: 'Vous acceptez les cartes?', english: 'Do you accept cards?', pronunciation: 'voo zak-sep-TAY lay KART' },
    { id: 58, category: 'Shopping', foreign: 'Je cherche...', english: "I'm looking for...", pronunciation: 'zhuh SHAIRSH' },
    { id: 59, category: 'Shopping', foreign: 'Je voudrais essayer ça.', english: 'I would like to try this.', pronunciation: 'zhuh voo-DRAY ay-say-AY sa' },
    { id: 60, category: 'Shopping', foreign: 'C\'est en solde?', english: 'Is it on sale?', pronunciation: 'say ton SOLD' },
    { id: 61, category: 'Shopping', foreign: 'Je prends celui-ci.', english: "I'll take this one.", pronunciation: 'zhuh PRON suh-LWEE see' },
    { id: 62, category: 'Shopping', foreign: 'Un reçu, s\'il vous plaît.', english: 'A receipt, please.', pronunciation: 'un ruh-SEW, seel voo PLEH' },

    // COMMON RESPONSES
    { id: 63, category: 'Common Responses', foreign: 'Oui, bien sûr.', english: 'Yes, of course.', pronunciation: 'wee, bee-an SYOOR' },
    { id: 64, category: 'Common Responses', foreign: 'Non, merci.', english: 'No, thank you.', pronunciation: 'non, mehr-SEE' },
    { id: 65, category: 'Common Responses', foreign: "D'accord.", english: 'Okay / Agreed.', pronunciation: 'da-KOR' },
    { id: 66, category: 'Common Responses', foreign: 'Pas de problème.', english: 'No problem.', pronunciation: 'pa duh pro-BLEM' },
    { id: 67, category: 'Common Responses', foreign: 'Je ne sais pas.', english: "I don't know.", pronunciation: 'zhuh nuh say PA' },
    { id: 68, category: 'Common Responses', foreign: 'Peut-être.', english: 'Maybe.', pronunciation: 'puh-TET-ruh' },
    { id: 69, category: 'Common Responses', foreign: 'Bien sûr!', english: 'Of course!', pronunciation: 'bee-an SYOOR' },
    { id: 70, category: 'Common Responses', foreign: 'Avec plaisir!', english: 'With pleasure!', pronunciation: 'a-VEK play-ZEER' },
    { id: 71, category: 'Common Responses', foreign: "C'est parfait.", english: "That's perfect.", pronunciation: 'say par-FAY' },
    { id: 72, category: 'Common Responses', foreign: 'Désolé(e).', english: 'Sorry.', pronunciation: 'day-zo-LAY' },
    { id: 73, category: 'Common Responses', foreign: 'Pas du tout.', english: 'Not at all.', pronunciation: 'pa dew TOO' },
    { id: 74, category: 'Common Responses', foreign: "C'est vrai.", english: "That's true.", pronunciation: 'say VRAY' },

    // EMERGENCIES
    { id: 75, category: 'Emergencies', foreign: 'Appelez le médecin!', english: 'Call a doctor!', pronunciation: 'ap-LAY luh may-duh-SAN' },
    { id: 76, category: 'Emergencies', foreign: 'Appelez la police!', english: 'Call the police!', pronunciation: 'ap-LAY la po-LEES' },
    { id: 77, category: 'Emergencies', foreign: 'Au secours!', english: 'Help!', pronunciation: 'oh suh-KOOR' },
    { id: 78, category: 'Emergencies', foreign: "J'ai besoin d'aide.", english: 'I need help.', pronunciation: 'zhay buh-ZWAN DAID' },
    { id: 79, category: 'Emergencies', foreign: 'Je suis malade.', english: 'I am sick.', pronunciation: 'zhuh swee ma-LAD' },
    { id: 80, category: 'Emergencies', foreign: "J'ai mal ici.", english: 'I have pain here.', pronunciation: 'zhay MAL ee-SEE' },
    { id: 81, category: 'Emergencies', foreign: "Où est l'hôpital?", english: 'Where is the hospital?', pronunciation: 'oo ay lo-pee-TAL' },
    { id: 82, category: 'Emergencies', foreign: "J'ai perdu mon passeport.", english: 'I lost my passport.', pronunciation: 'zhay pair-DEW mon pas-POR' },
    { id: 83, category: 'Emergencies', foreign: "On m'a volé.", english: "I've been robbed.", pronunciation: 'on ma vo-LAY' },
    { id: 84, category: 'Emergencies', foreign: "C'est une urgence.", english: "It's an emergency.", pronunciation: 'say ewn ur-ZHONS' },

    // HOTEL & ACCOMMODATION
    { id: 85, category: 'Hotel & Accommodation', foreign: "J'ai une réservation.", english: 'I have a reservation.', pronunciation: 'zhay ewn ray-zair-va-see-ON' },
    { id: 86, category: 'Hotel & Accommodation', foreign: 'Une chambre pour une nuit, s\'il vous plaît.', english: 'A room for one night, please.', pronunciation: 'ewn SHOM-bruh poor ewn NWEE, seel voo PLEH' },
    { id: 87, category: 'Hotel & Accommodation', foreign: 'À quelle heure est le check-out?', english: 'What time is check-out?', pronunciation: 'ah kel UR ay luh CHECK out' },
    { id: 88, category: 'Hotel & Accommodation', foreign: 'Avez-vous le Wi-Fi?', english: 'Do you have Wi-Fi?', pronunciation: 'a-VAY voo luh WEE-fee' },
    { id: 89, category: 'Hotel & Accommodation', foreign: "La climatisation ne fonctionne pas.", english: "The air conditioning doesn't work.", pronunciation: 'la klee-ma-tee-za-see-ON nuh fonk-see-ON pa' },
    { id: 90, category: 'Hotel & Accommodation', foreign: 'Où se trouve le petit-déjeuner?', english: 'Where is breakfast?', pronunciation: 'oo suh TROOV luh puh-tee day-zhuh-NAY' },

    // COMPLIMENTS & SMALL TALK
    { id: 91, category: 'Compliments & Small Talk', foreign: 'Votre pays est magnifique.', english: 'Your country is magnificent.', pronunciation: 'VOT-ruh pay-ee ay mahn-yee-FEEK' },
    { id: 92, category: 'Compliments & Small Talk', foreign: "J'aime beaucoup la culture française.", english: 'I really love French culture.', pronunciation: 'zhem boh-KOO la kul-TYOOR fron-SEZ' },
    { id: 93, category: 'Compliments & Small Talk', foreign: 'Vous avez de la chance.', english: 'You are lucky.', pronunciation: 'voo za-VAY duh la SHONS' },
    { id: 94, category: 'Compliments & Small Talk', foreign: 'Ce vin est excellent.', english: 'This wine is excellent.', pronunciation: 'suh VAN ay ek-say-LON' },
    { id: 95, category: 'Compliments & Small Talk', foreign: 'Quel beau temps!', english: 'What beautiful weather!', pronunciation: 'kel boh TOM' },
    { id: 96, category: 'Compliments & Small Talk', foreign: 'Je suis en vacances.', english: 'I am on vacation.', pronunciation: 'zhuh swee zon va-KONS' },
    { id: 97, category: 'Compliments & Small Talk', foreign: "C'est mon premier voyage en France.", english: 'This is my first trip to France.', pronunciation: 'say mon pruh-MYAY vwa-YAZH on FRONS' },
    { id: 98, category: 'Compliments & Small Talk', foreign: "J'espère revenir bientôt.", english: 'I hope to come back soon.', pronunciation: 'zhes-PAIR ruh-vuh-NEER bee-an-TOH' },
    { id: 99, category: 'Compliments & Small Talk', foreign: 'Les Français sont très accueillants.', english: 'The French are very welcoming.', pronunciation: 'lay fron-SAY son tray za-kuh-YON' },
    { id: 100, category: 'Compliments & Small Talk', foreign: 'Merci pour votre aide.', english: 'Thank you for your help.', pronunciation: 'mehr-SEE poor VOT-ruh AID' },

    // COMPLIMENTS
    { id: 101, category: 'Compliments', foreign: 'Tu es vraiment beau/belle aujourd\'hui.', english: 'You look really good today. (informal)', pronunciation: 'tew ay vray-MON boh/bel oh-zhoor-DWEE' },
    { id: 102, category: 'Compliments', foreign: 'Tu es vraiment beau/belle ce soir.', english: 'You look really good tonight. (informal)', pronunciation: 'tew ay vray-MON boh/bel suh SWAHR' },
    { id: 103, category: 'Compliments', foreign: 'Vous êtes très beau/belle.', english: 'You are very beautiful. (formal)', pronunciation: 'voo zet tray boh/bel' },
    { id: 104, category: 'Compliments', foreign: 'Tu es très beau/belle.', english: 'You are very beautiful. (informal)', pronunciation: 'tew ay tray boh/bel' },
    { id: 105, category: 'Compliments', foreign: 'J\'aime beaucoup ta tenue.', english: 'I really like your outfit.', pronunciation: 'zhem boh-KOO ta tuh-NEW' },
    { id: 106, category: 'Compliments', foreign: 'Tu as de beaux yeux.', english: 'You have beautiful eyes.', pronunciation: 'tew ah duh boh YUH' },
    { id: 107, category: 'Compliments', foreign: 'Tu es très élégant(e).', english: 'You are very elegant.', pronunciation: 'tew ay tray ay-lay-GON' },
    { id: 108, category: 'Compliments', foreign: 'Ça te va vraiment bien.', english: 'That looks really good on you.', pronunciation: 'sa tuh va vray-MON bee-AN' },
    { id: 109, category: 'Compliments', foreign: 'Tu es adorable.', english: 'You are adorable / lovely.', pronunciation: 'tew ay za-do-RA-bluh' },
    { id: 110, category: 'Compliments', foreign: 'Tu as un très beau sourire.', english: 'You have a beautiful smile.', pronunciation: 'tew ah un tray boh soo-REER' },
  
    // FLIRTING & ABOUT YOU
    { id: 111, category: 'About You', foreign: 'Tu fais quoi en dehors d\'être si belle ?', english: 'What do you do besides being so beautiful?', pronunciation: 'tew fay KWAH on deh-OHR det-ruh see bel' },
    { id: 112, category: 'About You', foreign: 'Tu es trop gentil(le) !', english: 'You\'re too sweet / too kind!', pronunciation: 'tew ay troh zhon-TEE' },
    { id: 113, category: 'About You', foreign: 'Tu me fais rougir !', english: 'You\'re making me blush!', pronunciation: 'tew muh fay roo-ZHEER' },
    { id: 114, category: 'About You', foreign: 'Je travaille dans la tech.', english: 'I work in tech.', pronunciation: 'zhuh tra-VY don la tek' },
    { id: 115, category: 'About You', foreign: 'J\'ai ma propre entreprise.', english: 'I own my own business.', pronunciation: 'zhay ma PRO-pruh on-truh-PREEZ' },
    { id: 116, category: 'About You', foreign: 'C\'est impressionnant !', english: 'That\'s impressive!', pronunciation: 'say eem-preh-syoh-NON' },
    { id: 117, category: 'About You', foreign: 'Dis-m\'en plus !', english: 'Tell me more!', pronunciation: 'dee-MON PLOO' },
  
    // STILL LEARNING
    { id: 118, category: 'Still Learning', foreign: 'Désolé(e), je ne comprends pas — j\'apprends encore le français.', english: 'Sorry, I don\'t understand — I\'m still learning French.', pronunciation: 'day-zo-LAY, zhuh nuh kom-PRON pah — zhah-PRON on-KOR luh fron-SAY' },

    // LOCAL LAUGHS
    { id: 119, category: 'Local Laughs', foreign: 'Allez les Bleus !', english: 'Come on France! (the national football team)', pronunciation: 'ah-LAY lay BLUH' },
    { id: 120, category: 'Local Laughs', foreign: 'C\'est pas faux.', english: 'That\'s not wrong. (the very French way of agreeing)', pronunciation: 'say pah FOH' },
    { id: 121, category: 'Local Laughs', foreign: 'Putain, c\'est bon !', english: 'Damn, that\'s good! (say this about the food)', pronunciation: 'poo-TAN, say BON' },
    { id: 122, category: 'Local Laughs', foreign: 'Bah oui, évidemment.', english: 'Well yes, obviously. (the most French sentence possible)', pronunciation: 'bah WEE, ay-vee-da-MON' },
    { id: 123, category: 'Local Laughs', foreign: 'Ça roule ?', english: 'Everything rolling? (casual: how\'s it going?)', pronunciation: 'sa ROOL' },
  ],

  culture: {
    overview: "France is known for its sophisticated joie de vivre — the art of good living. French culture places tremendous value on food, wine, art, philosophy, and lively intellectual debate. Parisians in particular have a reputation for being direct and private with strangers, but once you make the effort to speak even a little French, attitudes warm considerably.",
    people: "French people are proud of their culture and language. They tend to be formal with people they don't know well — always use 'vous' with strangers and elders. Don't be discouraged if shopkeepers seem distant; it's cultural, not personal. A simple 'Bonjour' when entering any shop is mandatory — skipping it is considered rude.",
    dining: "Meals are a sacred ritual. Lunch (déjeuner) and dinner (dîner) can last 2+ hours and are considered social events. It's rude to rush. Bread is always on the table and free. Tipping is not expected (service is included by law) but small tips are appreciated. Don't ask for a to-go box — it's not really a thing in traditional restaurants.",
    socialNorms: [
      "Always say Bonjour when entering a shop, restaurant, or elevator — it's basic politeness",
      "Use 'vous' (formal you) with strangers, waitstaff, and elders; switch to 'tu' only when invited",
      "La bise (cheek kisses): typically 2 in Paris, varies by region. Wait to see if the other person initiates",
      "Punctuality: be on time for formal meetings, but 15-30 min late is acceptable for dinner parties",
      "Discussing money, salaries, or personal wealth is considered very rude",
      "French people may argue passionately — this is normal and doesn't mean they're angry with you",
    ]
  },

  gestures: [
    { name: 'La Bise', emoji: '💋', description: 'Cheek kiss greeting — typically 2 kisses in Paris, but up to 4 in the south. Let the French person initiate it.' },
    { name: 'Mon Œil', emoji: '👁️', description: 'Pulling down the lower eyelid with one finger means "I don\'t believe you" or "Yeah right!"' },
    { name: 'Finger Kiss', emoji: '🤌', description: 'Bringing fingers to lips and kissing them means something is absolutely delicious or excellent.' },
    { name: 'La Barbe', emoji: '🙄', description: 'Stroking an imaginary beard on the chin signals boredom or annoyance — "How tedious!"' },
    { name: 'The Shrug', emoji: '🤷', description: 'The classic French shrug with a pursed lip and raised eyebrows means "I don\'t know" or "I don\'t care."' },
    { name: 'Se serrer la main', emoji: '🤝', description: 'Handshakes are common in professional settings. Always firm and brief.' },
  ],

  facts: [
    { emoji: '🗼', title: 'Most Visited Country', text: 'France is the most visited country in the world, welcoming over 90 million tourists annually.' },
    { emoji: '🥐', title: 'Bread Culture', text: 'The French eat 30 million baguettes every single day. There are strict laws about what a real baguette can contain.' },
    { emoji: '🍷', title: 'Wine is Life', text: 'France produces over 8 billion bottles of wine per year. Asking for ketchup or ordering a Coke with a fine meal may raise eyebrows.' },
    { emoji: '☕', title: 'Café Culture', text: 'Standing at a café bar (le zinc) is cheaper than sitting at a table. This is a beloved daily ritual for many French people.' },
    { emoji: '💊', title: 'Pharmacies Everywhere', text: 'French pharmacies (marked by a green cross) are incredibly helpful — pharmacists can recommend treatments for minor ailments without a prescription.' },
    { emoji: '🎨', title: 'Art Capital', text: 'The Louvre is the most visited art museum in the world. France has produced some of history\'s greatest artists, writers, and philosophers.' },
    { emoji: '🧀', title: 'Cheese Nation', text: 'France produces over 1,000 varieties of cheese. Charles de Gaulle famously said "How can you govern a country which has 246 varieties of cheese?"' },
    { emoji: '🚇', title: 'Paris Metro', text: 'The Paris Métro has 302 stations — no point in Paris is more than 500m from a station. It\'s one of the densest metro systems in the world.' },
  ],

  
};
