const ITALIAN_DATA = {
  language: 'Italian',
  langCode: 'it-IT',
  flag: '🇮🇹',
  color: '#009246',
  accent: '#CE2B37',

  words: [
    // GREETINGS
    { id: 1, category: 'Greetings', foreign: 'Ciao', english: 'Hi / Bye (informal)', pronunciation: 'CHOW' },
    { id: 2, category: 'Greetings', foreign: 'Buongiorno', english: 'Good morning / Good day', pronunciation: 'bwohn-JOR-noh' },
    { id: 3, category: 'Greetings', foreign: 'Buonasera', english: 'Good evening', pronunciation: 'bwoh-nah-SAY-rah' },
    { id: 4, category: 'Greetings', foreign: 'Buonanotte', english: 'Good night', pronunciation: 'bwoh-nah-NOT-teh' },
    { id: 5, category: 'Greetings', foreign: 'Arrivederci', english: 'Goodbye (formal)', pronunciation: 'ah-ree-veh-DAIR-chee' },
    { id: 6, category: 'Greetings', foreign: 'Grazie', english: 'Thank you', pronunciation: 'GRAT-tsee-eh' },
    { id: 7, category: 'Greetings', foreign: 'Prego', english: "You're welcome / Please", pronunciation: 'PRAY-goh' },
    { id: 8, category: 'Greetings', foreign: 'Per favore', english: 'Please', pronunciation: 'pair fa-VOH-reh' },
    { id: 9, category: 'Greetings', foreign: 'Sì', english: 'Yes', pronunciation: 'SEE' },
    { id: 10, category: 'Greetings', foreign: 'No', english: 'No', pronunciation: 'NOH' },

    // ESSENTIALS
    { id: 11, category: 'Essentials', foreign: 'Scusi', english: 'Excuse me (formal)', pronunciation: 'SKOO-zee' },
    { id: 12, category: 'Essentials', foreign: 'Mi dispiace', english: "I'm sorry", pronunciation: 'mee dees-pee-AH-cheh' },
    { id: 13, category: 'Essentials', foreign: 'Io', english: 'I', pronunciation: 'EE-oh' },
    { id: 14, category: 'Essentials', foreign: 'Lei', english: 'You (formal)', pronunciation: 'LAY' },
    { id: 15, category: 'Essentials', foreign: 'Tu', english: 'You (informal)', pronunciation: 'TOO' },
    { id: 16, category: 'Essentials', foreign: 'Noi', english: 'We', pronunciation: 'NOY' },
    { id: 17, category: 'Essentials', foreign: 'Qui', english: 'Here', pronunciation: 'KWEE' },
    { id: 18, category: 'Essentials', foreign: 'Là', english: 'There', pronunciation: 'LAH' },
    { id: 19, category: 'Essentials', foreign: 'Dove', english: 'Where', pronunciation: 'DOH-veh' },
    { id: 20, category: 'Essentials', foreign: 'Cosa', english: 'What', pronunciation: 'KOH-zah' },

    // NUMBERS
    { id: 21, category: 'Numbers', foreign: 'Uno', english: 'One', pronunciation: 'OO-noh' },
    { id: 22, category: 'Numbers', foreign: 'Due', english: 'Two', pronunciation: 'DOO-eh' },
    { id: 23, category: 'Numbers', foreign: 'Tre', english: 'Three', pronunciation: 'TRAY' },
    { id: 24, category: 'Numbers', foreign: 'Quattro', english: 'Four', pronunciation: 'KWAT-troh' },
    { id: 25, category: 'Numbers', foreign: 'Cinque', english: 'Five', pronunciation: 'CHEEN-kweh' },
    { id: 26, category: 'Numbers', foreign: 'Sei', english: 'Six', pronunciation: 'SAY' },
    { id: 27, category: 'Numbers', foreign: 'Sette', english: 'Seven', pronunciation: 'SET-teh' },
    { id: 28, category: 'Numbers', foreign: 'Otto', english: 'Eight', pronunciation: 'OT-toh' },
    { id: 29, category: 'Numbers', foreign: 'Nove', english: 'Nine', pronunciation: 'NOH-veh' },
    { id: 30, category: 'Numbers', foreign: 'Dieci', english: 'Ten', pronunciation: 'dee-EH-chee' },

    // FOOD & DRINK
    { id: 31, category: 'Food & Drink', foreign: 'Pane', english: 'Bread', pronunciation: 'PAH-neh' },
    { id: 32, category: 'Food & Drink', foreign: 'Acqua', english: 'Water', pronunciation: 'AK-kwah' },
    { id: 33, category: 'Food & Drink', foreign: 'Vino', english: 'Wine', pronunciation: 'VEE-noh' },
    { id: 34, category: 'Food & Drink', foreign: 'Caffè', english: 'Coffee / Espresso', pronunciation: 'kaf-FEH' },
    { id: 35, category: 'Food & Drink', foreign: 'Formaggio', english: 'Cheese', pronunciation: 'for-MAD-joh' },
    { id: 36, category: 'Food & Drink', foreign: 'Pollo', english: 'Chicken', pronunciation: 'POL-loh' },
    { id: 37, category: 'Food & Drink', foreign: 'Pesce', english: 'Fish', pronunciation: 'PEH-sheh' },
    { id: 38, category: 'Food & Drink', foreign: 'Birra', english: 'Beer', pronunciation: 'BEER-rah' },
    { id: 39, category: 'Food & Drink', foreign: 'Tè', english: 'Tea', pronunciation: 'TEH' },
    { id: 40, category: 'Food & Drink', foreign: 'Gelato', english: 'Ice cream', pronunciation: 'jeh-LAH-toh' },

    // TRANSPORT
    { id: 41, category: 'Transport', foreign: 'Taxi', english: 'Taxi', pronunciation: 'TAK-see' },
    { id: 42, category: 'Transport', foreign: 'Autobus', english: 'Bus', pronunciation: 'OW-toh-boos' },
    { id: 43, category: 'Transport', foreign: 'Treno', english: 'Train', pronunciation: 'TRAY-noh' },
    { id: 44, category: 'Transport', foreign: 'Metro', english: 'Subway', pronunciation: 'MEH-troh' },
    { id: 45, category: 'Transport', foreign: 'Stazione', english: 'Station', pronunciation: 'sta-TSYOH-neh' },
    { id: 46, category: 'Transport', foreign: 'Aeroporto', english: 'Airport', pronunciation: 'ah-eh-roh-POR-toh' },
    { id: 47, category: 'Transport', foreign: 'Albergo', english: 'Hotel', pronunciation: 'al-BAIR-goh' },
    { id: 48, category: 'Transport', foreign: 'Via', english: 'Street / Road', pronunciation: 'VEE-ah' },
    { id: 49, category: 'Transport', foreign: 'Sinistra', english: 'Left', pronunciation: 'see-NEES-trah' },
    { id: 50, category: 'Transport', foreign: 'Destra', english: 'Right', pronunciation: 'DES-trah' },

    // TIME
    { id: 51, category: 'Time', foreign: 'Oggi', english: 'Today', pronunciation: 'OD-jee' },
    { id: 52, category: 'Time', foreign: 'Domani', english: 'Tomorrow', pronunciation: 'doh-MAH-nee' },
    { id: 53, category: 'Time', foreign: 'Ieri', english: 'Yesterday', pronunciation: 'YEH-ree' },
    { id: 54, category: 'Time', foreign: 'Mattina', english: 'Morning', pronunciation: 'mat-TEE-nah' },
    { id: 55, category: 'Time', foreign: 'Sera', english: 'Evening', pronunciation: 'SEH-rah' },
    { id: 56, category: 'Time', foreign: 'Ora', english: 'Hour / Now', pronunciation: 'OH-rah' },
    { id: 57, category: 'Time', foreign: 'Adesso', english: 'Now', pronunciation: 'ah-DES-soh' },
    { id: 58, category: 'Time', foreign: 'Presto', english: 'Soon / Early', pronunciation: 'PRES-toh' },
    { id: 59, category: 'Time', foreign: 'Lunedì', english: 'Monday', pronunciation: 'loo-neh-DEE' },
    { id: 60, category: 'Time', foreign: 'Settimana', english: 'Week', pronunciation: 'set-tee-MAH-nah' },

    // ADJECTIVES
    { id: 61, category: 'Adjectives', foreign: 'Buono', english: 'Good', pronunciation: 'BWOH-noh' },
    { id: 62, category: 'Adjectives', foreign: 'Grande', english: 'Big / Great', pronunciation: 'GRAN-deh' },
    { id: 63, category: 'Adjectives', foreign: 'Piccolo', english: 'Small', pronunciation: 'PEEK-koh-loh' },
    { id: 64, category: 'Adjectives', foreign: 'Bello', english: 'Beautiful', pronunciation: 'BEL-loh' },
    { id: 65, category: 'Adjectives', foreign: 'Caro', english: 'Expensive / Dear', pronunciation: 'KAH-roh' },
    { id: 66, category: 'Adjectives', foreign: 'Libero', english: 'Free / Available', pronunciation: 'LEE-beh-roh' },
    { id: 67, category: 'Adjectives', foreign: 'Aperto', english: 'Open', pronunciation: 'ah-PAIR-toh' },
    { id: 68, category: 'Adjectives', foreign: 'Chiuso', english: 'Closed', pronunciation: 'KYOO-zoh' },
    { id: 69, category: 'Adjectives', foreign: 'Caldo', english: 'Hot / Warm', pronunciation: 'KAL-doh' },
    { id: 70, category: 'Adjectives', foreign: 'Freddo', english: 'Cold', pronunciation: 'FRED-doh' },

    // VERBS
    { id: 71, category: 'Verbs', foreign: 'Avere', english: 'To have', pronunciation: 'ah-VEH-reh' },
    { id: 72, category: 'Verbs', foreign: 'Essere', english: 'To be', pronunciation: 'ES-seh-reh' },
    { id: 73, category: 'Verbs', foreign: 'Andare', english: 'To go', pronunciation: 'an-DAH-reh' },
    { id: 74, category: 'Verbs', foreign: 'Volere', english: 'To want', pronunciation: 'voh-LEH-reh' },
    { id: 75, category: 'Verbs', foreign: 'Potere', english: 'To be able to', pronunciation: 'poh-TEH-reh' },
    { id: 76, category: 'Verbs', foreign: 'Sapere', english: 'To know', pronunciation: 'sah-PEH-reh' },
    { id: 77, category: 'Verbs', foreign: 'Fare', english: 'To do / make', pronunciation: 'FAH-reh' },
    { id: 78, category: 'Verbs', foreign: 'Venire', english: 'To come', pronunciation: 'veh-NEE-reh' },
    { id: 79, category: 'Verbs', foreign: 'Parlare', english: 'To speak', pronunciation: 'par-LAH-reh' },
    { id: 80, category: 'Verbs', foreign: 'Capire', english: 'To understand', pronunciation: 'kah-PEE-reh' },

    // SHOPPING
    { id: 81, category: 'Shopping', foreign: 'Quanto', english: 'How much', pronunciation: 'KWAN-toh' },
    { id: 82, category: 'Shopping', foreign: 'Prezzo', english: 'Price', pronunciation: 'PRET-tsoh' },
    { id: 83, category: 'Shopping', foreign: 'Negozio', english: 'Store', pronunciation: 'neh-GOT-see-oh' },
    { id: 84, category: 'Shopping', foreign: 'Mercato', english: 'Market', pronunciation: 'mer-KAH-toh' },
    { id: 85, category: 'Shopping', foreign: 'Comprare', english: 'To buy', pronunciation: 'kom-PRAH-reh' },
    { id: 86, category: 'Shopping', foreign: 'Soldi', english: 'Money', pronunciation: 'SOL-dee' },
    { id: 87, category: 'Shopping', foreign: 'Carta', english: 'Card', pronunciation: 'KAR-tah' },
    { id: 88, category: 'Shopping', foreign: 'Ricevuta', english: 'Receipt', pronunciation: 'ree-cheh-VOO-tah' },
    { id: 89, category: 'Shopping', foreign: 'Taglia', english: 'Size', pronunciation: 'TAH-lyah' },
    { id: 90, category: 'Shopping', foreign: 'Sconto', english: 'Discount', pronunciation: 'SKON-toh' },

    // EMERGENCY
    { id: 91, category: 'Emergency', foreign: 'Aiuto', english: 'Help', pronunciation: 'ah-YOO-toh' },
    { id: 92, category: 'Emergency', foreign: 'Medico', english: 'Doctor', pronunciation: 'MEH-dee-koh' },
    { id: 93, category: 'Emergency', foreign: 'Ospedale', english: 'Hospital', pronunciation: 'os-peh-DAH-leh' },
    { id: 94, category: 'Emergency', foreign: 'Polizia', english: 'Police', pronunciation: 'poh-LEET-see-ah' },
    { id: 95, category: 'Emergency', foreign: 'Emergenza', english: 'Emergency', pronunciation: 'eh-mer-JEN-tsah' },
    { id: 96, category: 'Emergency', foreign: 'Perso', english: 'Lost', pronunciation: 'PAIR-soh' },
    { id: 97, category: 'Emergency', foreign: 'Malato', english: 'Sick', pronunciation: 'mah-LAH-toh' },
    { id: 98, category: 'Emergency', foreign: 'Dolore', english: 'Pain', pronunciation: 'doh-LOH-reh' },
    { id: 99, category: 'Emergency', foreign: 'Bagno', english: 'Restroom / Bathroom', pronunciation: 'BAH-nyoh' },
    { id: 100, category: 'Emergency', foreign: 'Ambasciata', english: 'Embassy', pronunciation: 'am-ba-SHAH-tah' },
  ],

  phrases: [
    // GREETINGS & INTRODUCTIONS
    { id: 1, category: 'Greetings & Introductions', foreign: 'Buongiorno, come sta?', english: 'Good morning, how are you? (formal)', pronunciation: 'bwohn-JOR-noh, KOH-meh stah' },
    { id: 2, category: 'Greetings & Introductions', foreign: 'Ciao, come stai?', english: 'Hi, how are you? (informal)', pronunciation: 'CHOW, KOH-meh sty' },
    { id: 3, category: 'Greetings & Introductions', foreign: 'Sto bene, grazie.', english: "I'm doing well, thank you.", pronunciation: 'stoh BEH-neh, GRAT-tsee-eh' },
    { id: 4, category: 'Greetings & Introductions', foreign: 'E Lei?', english: 'And you? (formal)', pronunciation: 'eh LAY' },
    { id: 5, category: 'Greetings & Introductions', foreign: 'Mi chiamo Diego.', english: 'My name is Diego.', pronunciation: 'mee KYAH-moh Diego' },
    { id: 6, category: 'Greetings & Introductions', foreign: 'Piacere di conoscerla.', english: 'Pleased to meet you. (formal)', pronunciation: 'pyah-CHEH-reh dee koh-NOH-shair-lah' },
    { id: 7, category: 'Greetings & Introductions', foreign: 'Come si chiama?', english: 'What is your name? (formal)', pronunciation: 'KOH-meh see KYAH-mah' },
    { id: 8, category: 'Greetings & Introductions', foreign: 'Molto piacere.', english: 'Very pleased to meet you.', pronunciation: 'MOL-toh pyah-CHEH-reh' },
    { id: 9, category: 'Greetings & Introductions', foreign: 'Buona giornata!', english: 'Have a good day!', pronunciation: 'BWOH-nah jor-NAH-tah' },
    { id: 10, category: 'Greetings & Introductions', foreign: 'A presto!', english: 'See you soon!', pronunciation: 'ah PRES-toh' },
    { id: 11, category: 'Greetings & Introductions', foreign: 'A domani!', english: 'See you tomorrow!', pronunciation: 'ah doh-MAH-nee' },
    { id: 12, category: 'Greetings & Introductions', foreign: 'Buona serata!', english: 'Have a good evening!', pronunciation: 'BWOH-nah seh-RAH-tah' },

    // ABOUT YOURSELF
    { id: 13, category: 'About Yourself', foreign: 'Sono americano/a.', english: 'I am American.', pronunciation: 'SOH-noh ah-meh-ree-KAH-noh' },
    { id: 14, category: 'About Yourself', foreign: 'Vengo dagli Stati Uniti.', english: 'I come from the United States.', pronunciation: 'VEN-goh DAH-lyee STAH-tee oo-NEE-tee' },
    { id: 15, category: 'About Yourself', foreign: "Sto imparando l'italiano.", english: 'I am learning Italian.', pronunciation: 'stoh eem-pah-RAN-doh lee-tah-LYAH-noh' },
    { id: 16, category: 'About Yourself', foreign: "Il mio italiano non è molto buono.", english: 'My Italian is not very good.', pronunciation: 'eel MEE-oh ee-tah-LYAH-noh non eh MOL-toh BWOH-noh' },
    { id: 17, category: 'About Yourself', foreign: "Parlo un po' italiano.", english: 'I speak a little Italian.', pronunciation: 'PAR-loh oon poh ee-tah-LYAH-noh' },
    { id: 18, category: 'About Yourself', foreign: 'Il mio spagnolo e inglese sono migliori.', english: 'My Spanish and English are better.', pronunciation: 'eel MEE-oh spa-NYOH-loh eh een-GLEH-zeh SOH-noh mee-LYOH-ree' },
    { id: 19, category: 'About Yourself', foreign: 'Può parlare più lentamente?', english: 'Can you speak more slowly?', pronunciation: 'PWOH par-LAH-reh pyoo len-tah-MEN-teh' },
    { id: 20, category: 'About Yourself', foreign: 'Non capisco.', english: "I don't understand.", pronunciation: 'non kah-PEES-koh' },
    { id: 21, category: 'About Yourself', foreign: 'Può ripetere?', english: 'Can you repeat that?', pronunciation: 'PWOH ree-peh-TEH-reh' },
    { id: 22, category: 'About Yourself', foreign: 'Parla inglese?', english: 'Do you speak English?', pronunciation: 'PAR-lah een-GLEH-zeh' },

    // CONVERSATION STARTERS
    { id: 23, category: 'Conversation Starters', foreign: 'Di dove sei?', english: 'Where are you from? (informal)', pronunciation: 'dee DOH-veh say' },
    { id: 24, category: 'Conversation Starters', foreign: 'Cosa fai?', english: 'What do you do?', pronunciation: 'KOH-zah FY' },
    { id: 25, category: 'Conversation Starters', foreign: 'È la prima volta in Italia?', english: 'Is this your first time in Italy?', pronunciation: 'eh la PREE-mah VOL-tah een ee-TAH-lyah' },
    { id: 26, category: 'Conversation Starters', foreign: 'Le piace l\'Italia?', english: 'Do you like Italy?', pronunciation: 'leh PYAH-cheh lee-TAH-lyah' },
    { id: 27, category: 'Conversation Starters', foreign: 'Cosa consiglia?', english: 'What do you recommend?', pronunciation: 'KOH-zah kon-SEE-lyah' },
    { id: 28, category: 'Conversation Starters', foreign: 'È bellissimo qui.', english: "It's beautiful here.", pronunciation: 'eh bel-LEES-see-moh KWEE' },
    { id: 29, category: 'Conversation Starters', foreign: "Adoro l'Italia.", english: 'I love Italy.', pronunciation: 'ah-DOH-roh lee-TAH-lyah' },
    { id: 30, category: 'Conversation Starters', foreign: 'La cucina italiana è deliziosa.', english: 'Italian cuisine is delicious.', pronunciation: 'la koo-CHEE-nah ee-tah-LYAH-nah eh deh-lee-tsee-OH-zah' },
    { id: 31, category: 'Conversation Starters', foreign: "Com'è il tempo?", english: "What's the weather like?", pronunciation: 'koh-MEH eel TEM-poh' },
    { id: 32, category: 'Conversation Starters', foreign: 'Ha figli?', english: 'Do you have children?', pronunciation: 'ah FEE-lyee' },

    // FOOD & ORDERING
    { id: 33, category: 'Food & Ordering', foreign: 'Un tavolo per due, per favore.', english: 'A table for two, please.', pronunciation: 'oon TAH-voh-loh pair DOO-eh, pair fah-VOH-reh' },
    { id: 34, category: 'Food & Ordering', foreign: 'Il menù, per favore.', english: 'The menu, please.', pronunciation: 'eel meh-NOO, pair fah-VOH-reh' },
    { id: 35, category: 'Food & Ordering', foreign: 'Vorrei ordinare.', english: 'I would like to order.', pronunciation: 'vor-RAY or-dee-NAH-reh' },
    { id: 36, category: 'Food & Ordering', foreign: 'Prendo il piatto del giorno.', english: "I'll have the daily special.", pronunciation: 'PREN-doh eel PYAT-toh del JOR-noh' },
    { id: 37, category: 'Food & Ordering', foreign: 'Qual è la specialità?', english: "What's the specialty?", pronunciation: 'kwahl eh la speh-chah-lee-TAH' },
    { id: 38, category: 'Food & Ordering', foreign: 'Il conto, per favore.', english: 'The bill, please.', pronunciation: 'eel KON-toh, pair fah-VOH-reh' },
    { id: 39, category: 'Food & Ordering', foreign: 'È delizioso!', english: "It's delicious!", pronunciation: 'eh deh-lee-tsee-OH-zoh' },
    { id: 40, category: 'Food & Ordering', foreign: 'Sono allergico/a a...', english: 'I am allergic to...', pronunciation: 'SOH-noh al-LAIR-jee-koh ah' },
    { id: 41, category: 'Food & Ordering', foreign: 'Un bicchiere di vino rosso, per favore.', english: 'A glass of red wine, please.', pronunciation: 'oon bee-KYEH-reh dee VEE-noh ROS-soh, pair fah-VOH-reh' },
    { id: 42, category: 'Food & Ordering', foreign: "Dell'acqua, per favore.", english: 'Some water, please.', pronunciation: 'del-AK-kwah, pair fah-VOH-reh' },
    { id: 43, category: 'Food & Ordering', foreign: 'Il servizio è incluso?', english: 'Is the service included?', pronunciation: 'eel ser-VEET-tsee-oh eh een-KLOO-zoh' },
    { id: 44, category: 'Food & Ordering', foreign: 'Non mangio carne.', english: "I don't eat meat.", pronunciation: 'non MAN-joh KAR-neh' },

    // DIRECTIONS & TRANSPORT
    { id: 45, category: 'Directions & Transport', foreign: 'Dov\'è la stazione?', english: 'Where is the train station?', pronunciation: 'doh-VEH la sta-TSYOH-neh' },
    { id: 46, category: 'Directions & Transport', foreign: 'Come si arriva a...?', english: 'How do I get to...?', pronunciation: 'KOH-meh see ar-REE-vah ah' },
    { id: 47, category: 'Directions & Transport', foreign: 'A sinistra / A destra.', english: 'To the left / To the right.', pronunciation: 'ah see-NEES-trah / ah DES-trah' },
    { id: 48, category: 'Directions & Transport', foreign: 'Dritto.', english: 'Straight ahead.', pronunciation: 'DREET-toh' },
    { id: 49, category: 'Directions & Transport', foreign: 'È lontano?', english: 'Is it far?', pronunciation: 'eh lon-TAH-noh' },
    { id: 50, category: 'Directions & Transport', foreign: 'Mi chiami un taxi, per favore.', english: 'Please call me a taxi.', pronunciation: 'mee KYAH-mee oon TAK-see, pair fah-VOH-reh' },
    { id: 51, category: 'Directions & Transport', foreign: "All'aeroporto, per favore.", english: 'To the airport, please.', pronunciation: 'al-lah-eh-roh-POR-toh, pair fah-VOH-reh' },
    { id: 52, category: 'Directions & Transport', foreign: 'Un biglietto per..., per favore.', english: 'A ticket to..., please.', pronunciation: 'oon bee-LYET-toh pair, pair fah-VOH-reh' },
    { id: 53, category: 'Directions & Transport', foreign: 'A che ora parte il treno?', english: 'What time does the train leave?', pronunciation: 'ah keh OH-rah PAR-teh eel TRAY-noh' },
    { id: 54, category: 'Directions & Transport', foreign: 'Mi sono perso/a.', english: 'I am lost.', pronunciation: 'mee SOH-noh PAIR-soh' },

    // SHOPPING
    { id: 55, category: 'Shopping', foreign: 'Quanto costa?', english: 'How much does it cost?', pronunciation: 'KWAN-toh KOS-tah' },
    { id: 56, category: 'Shopping', foreign: 'È troppo caro.', english: "It's too expensive.", pronunciation: 'eh TROP-poh KAH-roh' },
    { id: 57, category: 'Shopping', foreign: 'Accettate carte?', english: 'Do you accept cards?', pronunciation: 'at-chet-TAH-teh KAR-teh' },
    { id: 58, category: 'Shopping', foreign: 'Cerco...', english: "I'm looking for...", pronunciation: 'CHAIR-koh' },
    { id: 59, category: 'Shopping', foreign: 'Vorrei provare questo.', english: 'I would like to try this.', pronunciation: 'vor-RAY proh-VAH-reh KWES-toh' },
    { id: 60, category: 'Shopping', foreign: 'È in saldo?', english: 'Is it on sale?', pronunciation: 'eh een SAL-doh' },
    { id: 61, category: 'Shopping', foreign: 'Prendo questo.', english: "I'll take this one.", pronunciation: 'PREN-doh KWES-toh' },
    { id: 62, category: 'Shopping', foreign: 'Una ricevuta, per favore.', english: 'A receipt, please.', pronunciation: 'OO-nah ree-cheh-VOO-tah, pair fah-VOH-reh' },

    // COMMON RESPONSES
    { id: 63, category: 'Common Responses', foreign: 'Sì, certo.', english: 'Yes, of course.', pronunciation: 'SEE, CHAIR-toh' },
    { id: 64, category: 'Common Responses', foreign: 'No, grazie.', english: 'No, thank you.', pronunciation: 'noh, GRAT-tsee-eh' },
    { id: 65, category: 'Common Responses', foreign: 'Va bene.', english: 'Okay / Alright.', pronunciation: 'vah BEH-neh' },
    { id: 66, category: 'Common Responses', foreign: 'Nessun problema.', english: 'No problem.', pronunciation: 'nes-SOON proh-BLEH-mah' },
    { id: 67, category: 'Common Responses', foreign: 'Non lo so.', english: "I don't know.", pronunciation: 'non loh SOH' },
    { id: 68, category: 'Common Responses', foreign: 'Forse.', english: 'Maybe.', pronunciation: 'FOR-seh' },
    { id: 69, category: 'Common Responses', foreign: 'Certamente!', english: 'Certainly!', pronunciation: 'chair-tah-MEN-teh' },
    { id: 70, category: 'Common Responses', foreign: 'Con piacere!', english: 'With pleasure!', pronunciation: 'kon pyah-CHEH-reh' },
    { id: 71, category: 'Common Responses', foreign: 'È perfetto.', english: "That's perfect.", pronunciation: 'eh pair-FET-toh' },
    { id: 72, category: 'Common Responses', foreign: 'Mi dispiace.', english: "I'm sorry.", pronunciation: 'mee dees-PYAH-cheh' },
    { id: 73, category: 'Common Responses', foreign: 'Per niente.', english: 'Not at all.', pronunciation: 'pair NYEN-teh' },
    { id: 74, category: 'Common Responses', foreign: 'Hai ragione.', english: "You're right.", pronunciation: 'eye rah-JOH-neh' },

    // EMERGENCIES
    { id: 75, category: 'Emergencies', foreign: 'Chiami un medico!', english: 'Call a doctor!', pronunciation: 'KYAH-mee oon MEH-dee-koh' },
    { id: 76, category: 'Emergencies', foreign: 'Chiami la polizia!', english: 'Call the police!', pronunciation: 'KYAH-mee la poh-LEET-see-ah' },
    { id: 77, category: 'Emergencies', foreign: 'Aiuto!', english: 'Help!', pronunciation: 'ah-YOO-toh' },
    { id: 78, category: 'Emergencies', foreign: 'Ho bisogno di aiuto.', english: 'I need help.', pronunciation: 'oh bee-ZOH-nyoh dee ah-YOO-toh' },
    { id: 79, category: 'Emergencies', foreign: 'Sono malato/a.', english: 'I am sick.', pronunciation: 'SOH-noh mah-LAH-toh' },
    { id: 80, category: 'Emergencies', foreign: 'Ho dolore qui.', english: 'I have pain here.', pronunciation: 'oh doh-LOH-reh KWEE' },
    { id: 81, category: 'Emergencies', foreign: "Dov'è l'ospedale?", english: 'Where is the hospital?', pronunciation: 'doh-VEH los-peh-DAH-leh' },
    { id: 82, category: 'Emergencies', foreign: 'Ho perso il passaporto.', english: 'I lost my passport.', pronunciation: 'oh PAIR-soh eel pas-sah-POR-toh' },
    { id: 83, category: 'Emergencies', foreign: 'Sono stato/a derubato/a.', english: "I've been robbed.", pronunciation: 'SOH-noh STAH-toh deh-roo-BAH-toh' },
    { id: 84, category: 'Emergencies', foreign: "È un'emergenza.", english: "It's an emergency.", pronunciation: 'eh oo-neh-mer-JEN-tsah' },

    // HOTEL & ACCOMMODATION
    { id: 85, category: 'Hotel & Accommodation', foreign: 'Ho una prenotazione.', english: 'I have a reservation.', pronunciation: 'oh OO-nah preh-noh-tah-TSYOH-neh' },
    { id: 86, category: 'Hotel & Accommodation', foreign: 'Una camera per una notte, per favore.', english: 'A room for one night, please.', pronunciation: 'OO-nah KAH-meh-rah pair OO-nah NOT-teh, pair fah-VOH-reh' },
    { id: 87, category: 'Hotel & Accommodation', foreign: 'A che ora è il check-out?', english: 'What time is check-out?', pronunciation: 'ah keh OH-rah eh eel CHECK-owt' },
    { id: 88, category: 'Hotel & Accommodation', foreign: 'Avete il Wi-Fi?', english: 'Do you have Wi-Fi?', pronunciation: 'ah-VEH-teh eel WEE-fee' },
    { id: 89, category: 'Hotel & Accommodation', foreign: "L'aria condizionata non funziona.", english: "The air conditioning doesn't work.", pronunciation: 'LAH-ree-ah kon-dee-tsyoh-NAH-tah non foon-TSYOH-nah' },
    { id: 90, category: 'Hotel & Accommodation', foreign: 'Dove si trova la colazione?', english: 'Where is breakfast?', pronunciation: 'DOH-veh see TROH-vah la koh-la-TSYOH-neh' },

    // COMPLIMENTS & SMALL TALK
    { id: 91, category: 'Compliments & Small Talk', foreign: 'Il vostro paese è magnifico.', english: 'Your country is magnificent.', pronunciation: 'eel VOS-troh pah-EH-zeh eh mah-NYEE-fee-koh' },
    { id: 92, category: 'Compliments & Small Talk', foreign: 'Amo molto la cultura italiana.', english: 'I really love Italian culture.', pronunciation: 'AH-moh MOL-toh la kool-TOO-rah ee-tah-LYAH-nah' },
    { id: 93, category: 'Compliments & Small Talk', foreign: 'Questo vino è eccellente.', english: 'This wine is excellent.', pronunciation: 'KWES-toh VEE-noh eh et-chel-LEN-teh' },
    { id: 94, category: 'Compliments & Small Talk', foreign: 'Che bel tempo!', english: 'What beautiful weather!', pronunciation: 'keh bel TEM-poh' },
    { id: 95, category: 'Compliments & Small Talk', foreign: 'Sono in vacanza.', english: 'I am on vacation.', pronunciation: 'SOH-noh een vah-KAN-tsah' },
    { id: 96, category: 'Compliments & Small Talk', foreign: 'È il mio primo viaggio in Italia.', english: 'This is my first trip to Italy.', pronunciation: 'eh eel MEE-oh PREE-moh VYAD-joh een ee-TAH-lyah' },
    { id: 97, category: 'Compliments & Small Talk', foreign: 'Spero di tornare presto.', english: 'I hope to come back soon.', pronunciation: 'SPEH-roh dee tor-NAH-reh PRES-toh' },
    { id: 98, category: 'Compliments & Small Talk', foreign: 'Gli italiani sono molto simpatici.', english: 'Italians are very friendly.', pronunciation: 'lyee ee-tah-LYAH-nee SOH-noh MOL-toh seem-PAH-tee-chee' },
    { id: 99, category: 'Compliments & Small Talk', foreign: 'La pasta qui è fantastica.', english: 'The pasta here is fantastic.', pronunciation: 'la PAH-stah KWEE eh fan-TAH-stee-kah' },
    { id: 100, category: 'Compliments & Small Talk', foreign: 'Grazie per il vostro aiuto.', english: 'Thank you for your help.', pronunciation: 'GRAT-tsee-eh pair eel VOS-troh ah-YOO-toh' },

    // COMPLIMENTS
    { id: 101, category: 'Compliments', foreign: 'Sei davvero bello/bella oggi.', english: 'You look really good today. (informal)', pronunciation: 'say dav-VEH-roh BEL-loh/BEL-lah OD-jee' },
    { id: 102, category: 'Compliments', foreign: 'Sei davvero bello/bella stasera.', english: 'You look really good tonight. (informal)', pronunciation: 'say dav-VEH-roh BEL-loh/BEL-lah sta-SEH-rah' },
    { id: 103, category: 'Compliments', foreign: 'Lei è molto bella/bello.', english: 'You are very beautiful. (formal)', pronunciation: 'LAY eh MOL-toh BEL-lah/BEL-loh' },
    { id: 104, category: 'Compliments', foreign: 'Sei molto bella/bello.', english: 'You are very beautiful. (informal)', pronunciation: 'say MOL-toh BEL-lah/BEL-loh' },
    { id: 105, category: 'Compliments', foreign: 'Mi piace molto il tuo outfit.', english: 'I really like your outfit.', pronunciation: 'mee PYAH-cheh MOL-toh eel TOO-oh OUT-fit' },
    { id: 106, category: 'Compliments', foreign: 'Hai degli occhi bellissimi.', english: 'You have beautiful eyes.', pronunciation: 'eye DEL-yee OK-kee bel-LEES-see-mee' },
    { id: 107, category: 'Compliments', foreign: 'Sei molto elegante.', english: 'You are very elegant.', pronunciation: 'say MOL-toh eh-leh-GAN-teh' },
    { id: 108, category: 'Compliments', foreign: 'Ti sta davvero bene.', english: 'That looks really good on you.', pronunciation: 'tee stah dav-VEH-roh BEH-neh' },
    { id: 109, category: 'Compliments', foreign: 'Sei adorabile.', english: 'You are adorable / lovely.', pronunciation: 'say ah-doh-RAH-bee-leh' },
    { id: 110, category: 'Compliments', foreign: 'Hai un sorriso bellissimo.', english: 'You have a beautiful smile.', pronunciation: 'eye oon sor-REE-zoh bel-LEES-see-moh' },
  ],

  culture: {
    overview: "Italy is a country where beauty, food, family, and style are treated as serious matters. Italians live with a philosophy called 'la dolce vita' (the sweet life) and 'bella figura' — the art of making a good impression and always presenting yourself well. Life is meant to be savored, not rushed.",
    people: "Italians are warm, expressive, and family-oriented. Physical contact (touching arms, hugging, kissing cheeks) is common among friends. In the south, hospitality is paramount — refusing food or drink can feel offensive. Italians are very proud of their regional identity; a Roman is not the same as a Milanese. Speak about their local food, wine, or art and they'll love you.",
    dining: "Lunch (pranzo) was traditionally the main meal of the day and can still last 1.5–2 hours in smaller towns. Never order a cappuccino after 11am — Italians believe the milk interferes with digestion after a meal. Dinner (cena) is usually after 8pm. Bread is brought to the table but has no butter; use it to soak up sauce (fare la scarpetta) — completely acceptable. Tipping is appreciated but not obligatory.",
    socialNorms: [
      "Always greet with 'Buongiorno' in the morning or 'Buonasera' in the evening when entering any establishment",
      "La bella figura: dress well, stand tall, and present yourself with care — Italians notice and appreciate it",
      "Two cheek kisses are standard when meeting friends (left cheek first), but handshakes are normal in formal settings",
      "Sunday is sacred family day — many shops close and life slows down considerably",
      "Never put cheese on seafood pasta — it's a serious faux pas in Italian dining culture",
      "Validate your bus/train ticket before boarding — inspectors will fine you even if you have a ticket",
    ]
  },

  gestures: [
    { name: 'Chin Flick', emoji: '🫤', description: 'Flicking the chin outward with the back of the fingers means "I don\'t know" or "I don\'t care." Common in the south.' },
    { name: 'Finger Purse', emoji: '🤌', description: 'All fingers pinched together pointing upward, shaken gently. Means "What do you want?" or "What are you saying?" — the most iconic Italian gesture.' },
    { name: 'Cheek Screw', emoji: '😋', description: 'Pressing an extended index finger into the cheek and twisting means something is extremely delicious.' },
    { name: 'Eyelid Pull', emoji: '👁️', description: 'Pulling down the lower eyelid with one finger means "I\'m watching you" or "Be careful."' },
    { name: 'Hand Kiss', emoji: '💋', description: 'Kissing the fingertips and releasing them outward signals something is perfect, excellent, or beautiful.' },
    { name: 'La Bise', emoji: '🤗', description: 'Two cheek kisses (left first) when greeting friends. In southern Italy it can be one kiss or an embrace.' },
  ],

  facts: [
    { emoji: '🏛️', title: 'UNESCO World Leader', text: 'Italy has more UNESCO World Heritage Sites than any other country in the world — over 58 sites.' },
    { emoji: '🍕', title: 'Pizza Origins', text: 'Pizza was invented in Naples in the 18th century. A true Neapolitan pizza has strict rules: wood-fired, San Marzano tomatoes, buffalo mozzarella.' },
    { emoji: '☕', title: 'Espresso Culture', text: 'Coffee at the bar standing up costs about €1. Sitting down at a café can cost 3x more. Never order a latte — you\'ll get a glass of milk.' },
    { emoji: '🚗', title: 'Aggressive Driving', text: 'Italian driving is famously chaotic, especially in cities like Rome and Naples. Lanes are suggestions. Motorcycles weave everywhere. Cross streets carefully.' },
    { emoji: '👗', title: 'Fashion Capital', text: 'Milan is one of the world\'s four major fashion capitals. Italy is home to Gucci, Prada, Versace, Armani, Fendi, and Dolce & Gabbana.' },
    { emoji: '🍝', title: 'Regional Pasta Rules', text: 'Every region has its own pasta shapes, sauces, and strict rules about what goes with what. Carbonara is Roman — cream in carbonara is blasphemy to Italians.' },
    { emoji: '🔔', title: 'Church Bells', text: 'Church bells ring throughout the day in Italian towns and cities. It\'s considered charming, not noise. Many Italians time their days by them.' },
    { emoji: '💊', title: 'Farmacie', text: 'Italian pharmacies (green cross sign) are very helpful for minor ailments. Pharmacists are highly trained and can recommend treatments without a prescription.' },
  ]
};
